### ISSUE TITLE
Member attribute patron_status is misspelled as patreon_status

### ISSUE THREAD

**Issue by talk2MeGooseman** [JayPeet/patreon-elixir#5]
https://github.com/JayPeet/patreon-elixir/blob/f761ca32f9b2321e3da18a7f71a436a1b156de3b/lib/api/v2/resources/member.ex#L15

Since this attribute is misspelled it is not grabbing the data correctly.

Let me know if you would like me to make a commit and on any specific branch to resolve it.

**Comment by JayPeet** [comment]
Contributions welcome!

Not had time to work on this project for a while, as busy with other stuff.

**Comment by JayPeet** [comment]
Ended up fixing this and bringing it into main. Thanks for reporting it :)
